In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

1. Import Dataset

In [94]:
train_dataset = pd.read_csv("titanic_train.csv")

In [95]:
test_dataset = pd.read_csv("titanic_test.csv")

In [96]:
train_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [97]:
train_dataset.describe(include = 'all')

PassengerId    Survived      Pclass                           Name  \
count    891.000000  891.000000  891.000000                            891   
unique          NaN         NaN         NaN                            891   
top             NaN         NaN         NaN  Allen, Miss. Elisabeth Walton   
freq            NaN         NaN         NaN                              1   
mean     446.000000    0.383838    2.308642                            NaN   
std      257.353842    0.486592    0.836071                            NaN   
min        1.000000    0.000000    1.000000                            NaN   
25%      223.500000    0.000000    2.000000                            NaN   
50%      446.000000    0.000000    3.000000                            NaN   
75%      668.500000    1.000000    3.000000                            NaN   
max      891.000000    1.000000    3.000000                            NaN   

         Sex         Age       SibSp       Parch    Ticket        Fare  \
count    891  714.000000  891.000000  891.000000       891  891.000000   
unique     2         NaN         NaN         NaN       681         NaN   
top     male         NaN         NaN         NaN  CA. 2343         NaN   
freq     577         NaN         NaN         NaN         7         NaN   
mean     NaN   29.699118    0.523008    0.381594       NaN   32.204208   
std      NaN   14.526497    1.102743    0.806057       NaN   49.693429   
min      NaN    0.420000    0.000000    0.000000       NaN    0.000000   
25%      NaN   20.125000    0.000000    0.000000       NaN    7.910400   
50%      NaN   28.000000    0.000000    0.000000       NaN   14.454200   
75%      NaN   38.000000    1.000000    0.000000       NaN   31.000000   
max      NaN   80.000000    8.000000    6.000000       NaN  512.329200   

              Cabin Embarked  
count           204      889  
unique          147        3  
top     C23 C25 C27        S  
freq              4      644  
mean            NaN      NaN  
std             NaN      NaN  
min             NaN      NaN  
25%             NaN      NaN  
50%             NaN      NaN  
75%             NaN      NaN  
max             NaN      NaN

In [98]:
train_dataset.shape

(891, 12)

In [99]:
test_dataset

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

2. Check Missing Data

In [100]:
print("Null value in training\n{}".format(train_dataset.isnull().sum()))

Null value in training
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [101]:
print("Null value in testing\n{}".format(test_dataset.isnull().sum()))

Null value in testing
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [102]:
print("Null value in training\n{}".format(train_dataset.duplicated().sum()))

Null value in training
0


In [103]:
print("Null value in testing\n{}".format(test_dataset.duplicated().sum()))

Null value in testing
0


In [104]:
print('Embarkation per ports \n{}'.format(train_dataset['Embarked'].value_counts()))

Embarkation per ports 
S    644
C    168
Q     77
Name: Embarked, dtype: int64


In [105]:
train_dataset['Embarked'].fillna(value = 'S', inplace = True)

In [106]:
print('Embarkation per ports \n{}'.format(train_dataset['Embarked'].value_counts()))

Embarkation per ports 
S    646
C    168
Q     77
Name: Embarked, dtype: int64


In [107]:
test_dataset['Fare'].fillna(value = test_dataset.Fare.mean(), inplace = True)

In [108]:
print("Null value in training\n{}".format(train_dataset.isnull().sum()))

Null value in training
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64


In [109]:
print("Null value in testing\n{}".format(test_dataset.isnull().sum()))

Null value in testing
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64


In [110]:
train_dataset['Age'].fillna(value = train_dataset.Age.mean(), inplace = True)

In [111]:
test_dataset['Age'].fillna(value = test_dataset.Age.mean(), inplace = True)

In [112]:
print('Cabin\n{}'.format(train_dataset['Cabin'].value_counts()))

Cabin
C23 C25 C27    4
G6             4
B96 B98        4
F33            3
C22 C26        3
              ..
B37            1
C70            1
B19            1
D7             1
E36            1
Name: Cabin, Length: 147, dtype: int64


In [113]:
train_dataset.drop(columns = ['Cabin'], inplace = True)

In [114]:
test_dataset.drop(columns = ['Cabin'], inplace = True)

In [115]:
print("Null value in training\n{}".format(train_dataset.isnull().sum()))

Null value in training
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


In [116]:
print("Null value in training\n{}".format(test_dataset.isnull().sum()))

Null value in training
PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


3. Encode Categorical Column

In [117]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [118]:
train_dataset_y =  train_dataset['Survived']

In [119]:
train_dataset_X= train_dataset.drop(columns = ['Survived', 'Name', 'PassengerId', 'Ticket'])

In [120]:
train_dataset_X

Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0         3    male  22.000000      1      0   7.2500        S
1         1  female  38.000000      1      0  71.2833        C
2         3  female  26.000000      0      0   7.9250        S
3         1  female  35.000000      1      0  53.1000        S
4         3    male  35.000000      0      0   8.0500        S
..      ...     ...        ...    ...    ...      ...      ...
886       2    male  27.000000      0      0  13.0000        S
887       1  female  19.000000      0      0  30.0000        S
888       3  female  29.699118      1      2  23.4500        S
889       1    male  26.000000      0      0  30.0000        C
890       3    male  32.000000      0      0   7.7500        Q

[891 rows x 7 columns]

In [121]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 6])] , remainder= 'passthrough')
train_dataset_X = np.array(ct.fit_transform(train_dataset_X))

In [122]:
train_dataset_X.shape

(891, 10)

In [123]:
train_dataset_X[0]

array([ 0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  3.  , 22.  ,  1.  ,  0.  ,
        7.25])

In [124]:
train_dataset_y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

4. Train Test Split

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_dataset_X, train_dataset_y, test_size = 0.2, random_state = 42)

5. Feature Scaling

In [126]:
from sklearn.preprocessing import StandardScaler

In [127]:
X_train[:, [6, 9]]

array([[ 45.5   ,  28.5   ],
       [ 23.    ,  13.    ],
       [ 32.    ,   7.925 ],
       ...,
       [ 41.    ,  14.1083],
       [ 14.    , 120.    ],
       [ 21.    ,  77.2875]])

In [128]:
scaler = StandardScaler().fit(X_train[:, [6, 9]])

In [129]:
X_train[:, [6, 9]] = scaler.transform(X_train[:, [6,9]])

X_test[:, [6, 9]]= scaler.transform(X_test[:, [6,9]])

In [130]:
X_train

array([[ 0.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , -0.07868358],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , -0.37714494],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , -0.47486697],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  2.        ,
         0.        , -0.35580399],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         2.        ,  1.68320121],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
         1.        ,  0.86074761]])

In [131]:
X_test

array([[ 0.        ,  1.        ,  1.        , ...,  1.        ,
         1.        , -0.33390078],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , -0.42528387],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , -0.47486697],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         5.        , -0.02308312],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.42528387],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.        , -0.30589933]])

6. Create Model

In [132]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [133]:
rfc = KNeighborsClassifier()

In [134]:
param_grid = { 
    'n_neighbors': [3, 5, 7, 9, 11],
    'leaf_size': [10, 20, 30],
    'weights': ['uniform', 'distance'],
    'algorithm':['auto', 'ball_tree', 'kd_tree'],
    'p':[1, 2],
    'metric' : ['minkowski','euclidean','manhattan']
   
}

In [135]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)

In [136]:
CV_rfc.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree'],
                         'leaf_size': [10, 20, 30],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']})

In [137]:
print(CV_rfc.best_params_)

{'algorithm': 'auto', 'leaf_size': 10, 'metric': 'minkowski', 'n_neighbors': 11, 'p': 1, 'weights': 'uniform'}


In [138]:
print(CV_rfc.best_score_)

0.8188220230473752


In [139]:
CV_rfc.best_estimator_.get_params()

{'algorithm': 'auto',
 'leaf_size': 10,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 11,
 'p': 1,
 'weights': 'uniform'}

In [140]:
y_pre = CV_rfc.predict(X_test)

In [141]:
from sklearn.metrics import classification_report

In [142]:
print(classification_report(y_test, y_pre))

              precision    recall  f1-score   support

           0       0.80      0.90      0.85       105
           1       0.82      0.69      0.75        74

    accuracy                           0.81       179
   macro avg       0.81      0.79      0.80       179
weighted avg       0.81      0.81      0.81       179



In [143]:
from sklearn.metrics import confusion_matrix

In [144]:
print(confusion_matrix(y_test, y_pre, normalize = 'true'))

[[0.8952381  0.1047619 ]
 [0.31081081 0.68918919]]
