In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1. Import Dataset

In [2]:
dataset = pd.read_csv("Model_Data.csv")

In [3]:
dataset.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

2. Check Missing Data

In [4]:
dataset.isnull().values.any()

False

3. Encoding Category Columns(N/A)

4. Split Training and Testing Dataset

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [7]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 0)

5. Feature Scaling(N/A)

6. Create Model

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
regressor = LinearRegression()

7. Model Training

In [12]:
regressor.fit(X_train, y_train)

LinearRegression()

8. Model Testing

In [13]:
y_pred = regressor.predict(X_test)

In [14]:
np.set_printoptions(precision=2)

In [15]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[431.43, 431.23],
       [458.56, 460.01],
       [462.75, 461.14],
       ...,
       [469.52, 473.26],
       [442.42, 438.  ],
       [461.88, 463.28]])

9. Model Evaluation

In [16]:
from sklearn.metrics import r2_score

In [17]:
R_Square = r2_score(y_test, y_pred)

In [18]:
R_Square

0.9325315554761303