In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

1. Import Dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [4]:
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

2. Check Missing Data

In [6]:
dataset.isnull().values.any()
#there is no missing value

False

3. Encoding Categorical Column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])] , remainder= 'passthrough')
dataset = np.array(ct.fit_transform(dataset))

In [12]:
dataset[0]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
       1.3689780e+05, 4.7178410e+05, 1.9226183e+05])

4. Split Training and Testing Dataset

In [13]:
from sklearn.model_selection import train_test_split

In [21]:
X = dataset[:, 0:6] 

In [24]:
y = dataset[:, -1]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

5. Feature Scaling

In [31]:
# feature scaling is not required

6. Create Model

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
regressor = LinearRegression()

7. Model Training

In [34]:
regressor.fit(X_train, y_train)

LinearRegression()

8. Model Testing

In [35]:
y_pred = regressor.predict(X_test)

In [36]:
y_pred

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230166,  67851.69209676,  98791.73374686,
       113969.43533013, 167921.06569551])

In [37]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

9. Model Evaluation

In [38]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [39]:
R_Square = r2_score(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)
RMSE = np.sqrt(MSE)

In [40]:
R_Square

0.9347068473282303

In [41]:
MAE

7514.2936596413765

In [42]:
MSE

83502864.03259295

In [43]:
RMSE

9137.990152795797

10. Model Visualization

In [44]:
# it's not applicable